### ISSUE TITLE
Cannot find module 'axios'

### ISSUE THREAD

**Issue by kbyszewski** [fss/solis-inverter#11]
On run on my raspberry pi, I get:
`module.js:549
    throw err;
    ^

Error: Cannot find module 'axios'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/PROJECTS/SOLIS_INVERTER/solis-inverter-master/lib/solis_inverter_client.js:1:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)`

even thou I can get a packge with wget:

`wget https://registry.npmjs.org/axios/-/axios-0.21.1.tgz
--2021-06-18 11:23:41--  https://registry.npmjs.org/axios/-/axios-0.21.1.tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 104.16.22.35, 104.16.16.35, 104.16.17.35, ...
Connecting to registry.npmjs.org (registry.npmjs.org)|104.16.22.35|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 95962 (94K) [application/octet-stream]
Saving to: ‘axios-0.21.1.tgz’

axios-0.21.1.tgz                                   100%[=============================================================================================================>]  93.71K  --.-KB/s    in 0.007s

2021-06-18 11:23:41 (12.2 MB/s) - ‘axios-0.21.1.tgz’ saved [95962/95962]`

**Comment by fss** [comment]
just cloned the project, did npm i and started it without any issues.
try removing node_modules dir and install again

**Comment by kbyszewski** [comment]
Thanks for quick reply, I think I got it.
By default when you install node on raspbery pi with 
sudo apt-get install -y nodejs
you get node 8.11.1

Once I manually upgraded with
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs

I got node 16.3.0

Then 
npm i axion

and now it is running fine
